### ISSUE TITLE
wishlist: convert uses of LWP to HTTP::Tiny

### ISSUE THREAD

**Issue by karenetheridge** [rjbs/CPAN-Uploader#20]
I bet the usages of LWP::\* could be switched to HTTP::Tiny, which is smaller as well as being in core for newer perls.

This is a good candidate for the Pull Request Challenge. :)

**Comment by Grinnz** [comment]
HTTP::Tiny doesn't have multipart support natively, but perhaps https://metacpan.org/pod/HTTP::Tiny::Multipart could be used.

**Comment by sergeyromanov** [comment]
Just throwing my 2 cents here: I've created [Alt::CPAN::Uploader::tinyua](https://metacpan.org/pod/Alt::CPAN::Uploader::tinyua) to scratch the itch in question, but since then upstream `CPAN::Uploader` went a bit further.
Also, the whole `Alt::` namespace idea didn't get much traction, from what can see.

**Comment by djzort** [comment]
LWP supports psgi so its magic for testing :)

**Comment by Leont** [comment]
> I bet the usages of LWP::* could be switched to HTTP::Tiny, which is smaller as well as being in core for newer perls.

You've pretty much described [CPAN::Upload::Tiny](https://metacpan.org/pod/CPAN::Upload::Tiny) (though it isn't as feature-complete as `CPAN::Uploader`)

**Comment by rjbs** [comment]
I'm not super interested in doing this.  It might be in core, but SSL is not, and as long as you're installing things, install LWP.  I basically never use HTTP::Tiny, because on the rare occasions it bites me, it leaves a scar.
